spring:
  application:
    name: gateway-service
  profiles:
    active: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: gateway-service,config-client
      username: user
      password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka/, http://discovery-service-2:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: gateway-service