spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: user
      password: ${JASYPT_ENCRYPTOR_PASSWORD}

log:
  app-name: kafka-to-elastic-service